name: hydratex_rx
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/luanemanuel/hydrated_rx

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.1
  rxdart: ^0.27.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
